name: Sincronizar TC BCB a Supabase

on:
  schedule:
    # 12:30 UTC = 08:30 AM hora de Bolivia (UTC-4)
    - cron: '30 12 * * *'
  workflow_dispatch: # Botón manual para probar cuando quieras

jobs:
  ejecutar_sincronizacion:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar librerías
        run: pip install -r requirements.txt

      - name: Ejecutar bot
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python main.py
